[package]
name = "simplexsolver"
version = "0.1.0"
edition = "2018"

[lib]
name = "simplexsolver"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
"num" = "0.4.0"
"matrix" = "0.22.0"